spring.application.name=literalura

gutendex.api.url=https://gutendex.com/books?search=

spring.datasource.url=jdbc:postgresql://localhost:5432/literalura
spring.datasource.username=${DB_LITERALURA_USER}
spring.datasource.password=${DB_LITERALURA_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
